apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hello-tls-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        # Secret must be in istio-system (same namespace as ingressgateway)
        # and created with: kubectl create secret tls hello-sourceless-tls ...
        credentialName: hello-sourceless-tls
      hosts:
        - "hello-sourceless.default.example.com"
