apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tls-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  # SIMPLE TLS: server cert + key for hello-sourceless.default.example.com
  - hello-sourceless-tls.enc.yaml
  # MUTUAL TLS: server cert, key, and CA for hello-sourceless-mtls.default.example.com
  - hello-sourceless-mtls.enc.yaml
  # EGRESS mTLS: client cert, key, CA for outbound calls from the sidecar
  - egress-client-creds.enc.yaml
